packages:
  - 'packages/*'
  - 'apps/*'
  - 'examples/*'

catalog:
  vue: ^3.5.22
  '@types/node': ^24.9.1
  '@vitejs/plugin-vue': ^6.0.1
  '@vue/tsconfig': ^0.8.1
  typescript: ^5.9.3
  vite: npm:rolldown-vite@7.1.14
  vue-tsc: ^3.1.0
  '@eslint/js': ^9.38.0
  eslint: ^9.38.0
  globals: ^16.4.0
  jiti: ^2.6.1
  prettier: ^3.6.2
  tsx: ^4.20.6
  typescript-eslint: ^8.46.2
  vite-plugin-dts: ^4.5.4
